### ISSUE TITLE
open changelog in new page rather than current page

### ISSUE THREAD

**Issue by multinerd** [Decimation/decimation.github.io#1]
when clicking on screenshots or full changelog, the new page replaces the depiction page rather than opening a new page thus forcing you back to the repo page rather than the depiction index.html

if my explanation confuses you, on your repo, view screenshots and then try and go back and view your changelog. theres no way to get back to the original depiction index from screenshots or changelog

**Comment by Decimation** [comment]
It's a known issue. This is a bit trivial as you can just re-view the package in Cydia to "go back". I'll try to write a back button though...
